# Use an official Node.js runtime as a parent image
FROM --platform=linux/amd64 node:slim

# Set the working directory in the container
WORKDIR /usr/src/app

# Create and configure the entrypoint script
RUN echo '#!/bin/sh\nset -e\nexec "$@"' > /usr/local/bin/docker-entrypoint.sh && \
    chmod +x /usr/local/bin/docker-entrypoint.sh

# Copy package.json and package-lock.json to the container
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application source code to the container
COPY . .

# Expose port 3000 to the outside world
EXPOSE 3000

# Set the entrypoint and command
ENTRYPOINT ["/usr/local/bin/docker-entrypoint.sh"]
CMD ["npm", "start"]
